# Site settings
# Enter your own credentials here
title: "Processing-Structure Linkages"
email: dipen@patel.com
description: >
  Tell us about your site
baseurl: "/MIC-Process-Structure-Linkages" # replace ``/research-pages`` with the name of the parents repository
url: "Materials-Informatics-Lab.github.io" # replate ``Materials-Informatics-Lab`` with your Github username
twitter_username: twitterhandle
disqus: tonyfast

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5


gh:
  user: PenPatel
  repo: MIC-Process-Structure-Linkages
  # Branch hosting Github pages
  branch: gh-pages
